### ISSUE TITLE
feat: Supports handling carriage returns and commands beginning with #

### ISSUE THREAD

**Issue by huang12zheng** [trane-project/trane-cli#15]
* motion
Supports handling carriage returns(\n or '') and commands beginning with #
Currently trane only supports commands, but sometimes customers will interpret the commands

For example, the following scenario:
https://asciinema.org/a/3DTwksv3htBp0ALH9qnsBt1NN

**Comment by martinmr** [comment]
Merged the PR so I am closing this issue.
